name: Build & Deploy App
run-name: Build & Deploy Poketracker App 🚀
on: [ push ]
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm install
      - name: Build Angular App
        run: npm run build
      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/poketracker
          env:
           CI: true
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
