name: Build & Deploy App
run-name: Build & Deploy Poketracker App 🚀
on: [ push ]
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Create environments folder
        run: 'mkdir src/environments'
      - name: Create environments file
        run: 'touch src/environments/environments.ts'
      - name: Set up environments
        env:
          FIREBASE_API_KEY: ${{secrets.FIREBASE_API_TOKEN}}
        run: |
          echo "export const environment = { FIREBASE_API_KEY: '$FIREBASE_API_KEY', APP_NAME: 'Pokétracker' };" > src/environments/environment.ts
        shell: bash
      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm install
      - name: Build Angular App
        run: npm run build
      - name: Deploy to gh pages
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx angular-cli-ghpages --no-silent --name="${{ secrets.UNAME }}" --email=${{ secrets.EMAIL }}
